In [ ]:
#1.Why does this train-test split fail?
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=1.2, random_state=42)


In [ ]:
NameError : name train_test_split is not defined

In [ ]:
#2.
# from sklearn.tree import DecisionTreeClassifier

X = [[1, 2], [3, 4], [5, 6]]
y = [0, 1, 0]

model = DecisionTreeClassifier(max_depth=100)
model.fit(X, y)
print(model.score(X, y))


1.0


In [ ]:
NameError: name 'DecisionTreeClassifier' is not defined

In [ ]:
#3.
# from sklearn.cluster import KMeans
import numpy as np

X = np.array([[1, 2], [3, 4], [5, 6]])

model = KMeans(n_clusters=5)
model.fit(X)

In [ ]:
NameError: name 'KMeans' is not defined

In [ ]:
#4.
import padas as pd  

df = pd.DataFrame({'A': [1, 2, 3]})
print(df)

In [ ]:
NameError: name 'padas' is not defined. The correct module name is 'pandas'

In [ ]:
#5.from sklearn.tree import DecisionTreClassifier  # Typo in 'DecisionTreeClassifier'

from sklearn.tree import DecisionTreClassifier  # Typo in 'DecisionTreeClassifier'

model = DecisionTreClassifier()



In [ ]:
ImportError: cannot import name 'DecisionTreClassifier' from 'sklearn.tree'

In [ ]:
#6.
from sklearn.tree import DecisionTreeClassifier

model = DecisionTreeClassifier(depth=3)  


In [ ]:
TypeError : __init__() got an unexpected keyword argument 'depth'

In [ ]:
#7.
from sklearn.linear_model import LinearRegression

X = [[1], [2], [3], [4]]
y = [2, 4, 6, 8]

model = LinearRegression()
model.fit(X, y)

print(model.coef)  # Incorrect attribute name


In [ ]:
coefficients = model.coef_  # Correct attribute name

In [ ]:
#8.
from sklearn.neighbors import KNeighborsClassifier

X_train = [[1, 2], [3, 4], [5, 6]]
y_train = [0, 1, 0]

model = KNeighborsClassifier(n_neighbors=0)  # Invalid value for n_neighbors
model.fit(X_train, y_train)


In [ ]:
InvalidParameterError: n_neighbors=0 is not valid. n_neighbors must be greater than 0. 

In [ ]:
#9.
import pandas as pd

df = pd.DataFrame({'A': [10, 20, 30], 'B': [1, 2, 3]})
print(df.iloc['A'])  # Incorrect: iloc requires integer indexes


In [ ]:
IndexError: expects integer indexers but got 'A'print(df.loc['A'])  # Correct: loc can use label-based indexing

In [ ]:
#10.
from sklearn.ensemble import RandomForestClassifier

X_train = [[1, 2], [3, 4], [5, 6]]
y_train = [0, 1, 0]

model = RandomForestClassifier()
model.fit(X_train, y_train)

probs = model.predict_proba([[2,2]])[1]  # Incorrect index
print(probs)


In [ ]:
IndexError: index 1 is out of bounds for axis 0 with size 1
    
array([[0.8, 0.2]])
access probs[0][1]

In [15]:
model.predict([[3, 5]])  # Incorrect index --- IGNORE ---

array([1])

The predict_proba() method in scikit-learn is used by classification models to return the probability estimates for each possible class for a given input, rather than just the final class label

**Simple explanation:**

### `predict_proba([2,2])`

```python
[[0.74 0.26]]
```

* The model gives **probabilities for each class**
* Class 0 → **0.74 (74%)**
* Class 1 → **0.26 (26%)**

### `predict([2,2])`

```python
array([1])
```

* The model chooses the **final class label**
* It picks the class with the **higher decision score**
* So the output is **class 1**

### In short:

* **`predict_proba()` → confidence (probabilities)**
* **`predict()` → final decision final answer (class label)**

That’s why the outputs are different.
